# Generated by Django 5.1.7 on 2025-03-20 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='crime_execution',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='culprit_actions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
